"""add logo col

Revision ID: 55c524038a51
Revises: 2d682979b729
Create Date: 2025-11-24 16:00:33.101122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55c524038a51'
down_revision: Union[str, Sequence[str], None] = '2d682979b729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_boards', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_boards', 'logo_url')
    # ### end Alembic commands ###
