"""update JobPosts to include isOpen

Revision ID: bf61c1f9058a
Revises: 70f16919b782
Create Date: 2025-11-25 15:03:46.878268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf61c1f9058a'
down_revision: Union[str, Sequence[str], None] = '70f16919b782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('isOpen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'isOpen')
    # ### end Alembic commands ###
