"""add cascade relationship between jobposts and jobapplications

Revision ID: f62843fcfc9d
Revises: bf61c1f9058a
Create Date: 2025-11-26 11:17:00.585045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62843fcfc9d'
down_revision: Union[str, Sequence[str], None] = 'bf61c1f9058a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
